manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: hnbn
      url-base: https://github.com/HNBN9

  projects:
    - name: zmk
      import:
        file: app/west.yml
        path-prefix: external
      clone-depth: 1

    - name: zmk-pmw3610-driver
      path: external/zmk-pmw3610-driver
      clone-depth: 1

    - name: zmk-feature-default-layer
      path: external/zmk-feature-default-layer
      clone-depth: 1

    - name: zmk-driver-ext-power-transient
      path: external/zmk-driver-ext-power-transient
      clone-depth: 1

  self:
    path: config
