manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: hnbn
      url-base: https://github.com/HNBN9

  projects:
    - name: zmk
      remote: zmkfirmware
      revision : main
      import: app/west.yml
    - name: zmk-pmw3610-driver
      remote: hnbn
      revision: main

  self:
    path: config
