manifest:
  defaults:
    remote: zmkfirmware
    revision: main

  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware

  projects:
    - name: zmk
      path: external/zmk
      import:
        file: app/west.yml
      clone-depth: 1

  self:
    path: config
