manifest:
  version: 1.2

  defaults:
    remote: zmkfirmware
    revision: main

  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware

    - name: badjeff
      url-base: https://github.com/badjeff

  projects:
    - name: zmk
      remote: zmkfirmware
      import:
        file: app/west.yml
        path-prefix: external
      clone-depth: 1

    - name: zmk-pmw3610-driver
      remote: badjeff
      path: external/zmk-pmw3610-driver
      clone-depth: 1

  self:
    path: config
